name: May Linn
favicon: null
layout_spectrum: 0.08107775705866516
typography_spectrum: 0.9138254558201879
title: Personlig Trener May Linn Nirisrud
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1C1D21'
    - '#31353D'
    - '#445878'
    - '#92CDCF'
    - '#EEEFF7'
  brandStrength: 0.1673211499582976
  lightness: 0.8979893894866109
  saturation: 0.6206816306803375
  rhythmicContrast: 0.8641130207106471
purpose: []
