name: May Linn
favicon: null
layout_spectrum: 0.75627
typography_spectrum: 0.50537
title: Personlig Trener May Linn Nirisrud
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#00152a'
    - '#0954ff'
    - '#0bb7ff'
    - '#fefefb'
    - '#b2b2b1'
  brandStrength: 0
  lightness: 0.8125
  saturation: 0.8125
  rhythmicContrast: 1
purpose: []
