name: May Linn
favicon: null
layout_spectrum: 0.48924
typography_spectrum: 0.50537
title: Personlig Trener May Linn Nirisrud
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#4a4339'
    - '#37363b'
    - '#585c4d'
    - '#707c72'
  brandStrength: 0.5
  lightness: 0.1875
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
