name: May Linn
favicon: null
layout_spectrum: 0
typography_spectrum: 0.50537
title: Personlig Trener May Linn Nirisrud
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#7d8b96'
    - '#010101'
    - '#bdc7d1'
    - '#2b343b'
    - '#f4f8fb'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.015268699266016483
  rhythmicContrast: 1
purpose: []
