layout_spectrum: 0.5308709593955427
typography_spectrum: 0.699091303627938
color:
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
  brandStrength: 0.9236636103596538
  lightness: 0.6219462393783033
  saturation: 0.7058062176220119
  rhythmicContrast: 0.6601497535593808
opengraph:
  image: >-
    https://the-grid-user-content.s3-us-west-2.amazonaws.com/bbdd1633-6536-4625-a377-98245028b3f9.jpg
  type: null
  appId: 'https://www.facebook.com/PT.MayLinn/'
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: May Linn
  email: Maylinn.nirisrud@satselixia.ni
  url: www.maylinn.com
logo: null
name: MayLinn.com
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Kontakt
    id: 27f9d914-b73a-4be9-aa6e-7a35b370b958
    type: content
  - name: Om meg
    id: 2e2378d0-7301-46ec-85a7-d2fb75aba0d1
    type: content
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: "TRENING\_OG\_LIVSSTIL"
description: May Linn Nirisrud
purpose: []
