name: 'MayLinn '
favicon: null
layout_spectrum: 0.12920482573099434
typography_spectrum: 0.6497610958758742
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1c1c1c'
    - '#424242'
    - '#efefef'
    - '#646464'
    - '#bcbcbc'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.015268699266016483
  rhythmicContrast: 0.20770132448524237
purpose: []
